import collections

HyperParameters = collections.namedtuple('hyperparameters',
                                         ['batch_size',
                                          'noise_dim',
                                          'img_shape',
                                          'num_gens',
                                          'num_classes',
                                          'epochs',
                                          'logdir',
                                          'savedir',
                                          'gen_img_dir',
                                          'gen_lr', 'disc_lr',
                                          'beta_1', 'beta_2',
                                          'gp_weight',
                                          'disc_iters_per_gen_iter',
                                          'save_freq', 'save_img_num'])

hps = HyperParameters(batch_size=512,
                      noise_dim=128,
                      img_shape=(32, 32, 1),
                      num_gens=2,
                      num_classes=11,
                      epochs=20,
                      logdir='./logs/fit',
                      savedir='./models/',
                      gen_img_dir='./generated_images/',
                      gen_lr=0.0002, disc_lr=0.0002,
                      beta_1=0.5, beta_2=0.9,
                      gp_weight=10.0,
                      disc_iters_per_gen_iter=3,
                      save_freq=5,
                      save_img_num=4)
